name: GitOps Automation
on: [push] # Робот прокидається при кожному збереженні

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Simulate Config Check
        run: |
          echo "Перевірка файлів OpenHAB..."
          echo "Синтаксис Items: OK"
          echo "Синтаксис Rules: OK"

      - name: Deploy to Edge Node
        run: |
          echo "Розгортання конфігурації на шлюз..."
          echo "Версія оновлена успішно!"
